// <auto-generated />
using System;
using EmployeeManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250920195602_Reports")]
    partial class Reports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeeManagementAPI.Models.DTO.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 463, DateTimeKind.Utc).AddTicks(7283),
                            Email = "admin@company.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$5bha7qwgleihq3op.c7yhuEN0hzNwgrIewLpovVs7hSKPhwjVvK/O",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 612, DateTimeKind.Utc).AddTicks(7185),
                            Email = "hr@company.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$.ylqWx5ene8mKkK8G.dIXu3.UTHrVloPOW4BAiqrkNbZulEMbru9W",
                            Role = "HR",
                            Username = "hruser"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 781, DateTimeKind.Utc).AddTicks(287),
                            Email = "employee1@company.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$bZvDlMQAdya0wTQCQlBLh.dnz./cwBTruACnmEHVGfMMGkNBieKVe",
                            Role = "Employee",
                            Username = "employee1"
                        });
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<TimeSpan?>("WorkingHours")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 948, DateTimeKind.Utc).AddTicks(1893),
                            Date = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            Notes = "On time",
                            Status = "Present"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 948, DateTimeKind.Utc).AddTicks(1902),
                            Date = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            Notes = "On time",
                            Status = "Present"
                        });
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 463, DateTimeKind.Utc).AddTicks(7142),
                            Description = "HR Department",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 463, DateTimeKind.Utc).AddTicks(7145),
                            Description = "IT Department",
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 463, DateTimeKind.Utc).AddTicks(7146),
                            Description = "Finance Department",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 463, DateTimeKind.Utc).AddTicks(7147),
                            Description = "Marketing Department",
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 948, DateTimeKind.Utc).AddTicks(1842),
                            DepartmentId = 2,
                            Email = "john.doe@company.com",
                            FirstName = "John",
                            HireDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Doe",
                            Phone = "123-456-7890",
                            Position = "Software Engineer",
                            Salary = 60000.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 20, 19, 56, 1, 948, DateTimeKind.Utc).AddTicks(1845),
                            DepartmentId = 1,
                            Email = "jane.smith@company.com",
                            FirstName = "Jane",
                            HireDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Smith",
                            Phone = "098-765-4321",
                            Position = "HR Manager",
                            Salary = 75000.00m
                        });
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Attendance", b =>
                {
                    b.HasOne("EmployeeManagementAPI.Models.Data.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Employee", b =>
                {
                    b.HasOne("EmployeeManagementAPI.Models.Data.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Data.Employee", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
